### ISSUE TITLE
New release for pytest 7.2 compatibility?

### ISSUE THREAD

**Issue by The-Compiler** [pytest-dev/pytest-bdd#568]
Running pytest-bdd with pytest 7.2 ([released a week ago](https://github.com/pytest-dev/pytest/releases/tag/7.2.0)) leads to:

```
pytest.PytestDeprecationWarning: The hookimpl pytest_bdd_after_step uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
 at .../pytest_bdd/plugin.py:110
```

This was fixed by @nicoddemus a few months ago:

- #549 

but it looks like 689b6a9385c3622759e5e3387d21ef0f673fe2ad hasn't made it into a release so far?

**Comment by drothlis** [comment]
There's also this CI failure seen in https://github.com/pytest-dev/pytest-bdd/pull/570#issuecomment-1301953329: 

    INTERNALERROR>     tw = py.io.TerminalWriter()
    INTERNALERROR> AttributeError: module 'py' has no attribute 'io'

pytest 7.2.0 (2022-10-23) [release notes] say:

> [#10396](https://github.com/pytest-dev/pytest/issues/10396): pytest no longer depends on the `py` library. pytest provides a vendored copy of `py.error` and `py.path` modules but will use the `py` library if it is installed. If you need other `py.*` modules, continue to install the deprecated `py` library separately, otherwise it can usually be removed as a dependency.

[release notes]: https://docs.pytest.org/en/stable/changelog.html#pytest-7-2-0-2022-10-23

**Comment by drothlis** [comment]
> There's also this CI failure seen in [#570 (comment)](https://github.com/pytest-dev/pytest-bdd/pull/570#issuecomment-1301953329):

Fixed in #571.

**Comment by youtux** [comment]
Right, I’ll make a release by the end of the weekend, thanks for notifying us

**Comment by youtux** [comment]
pytest_bdd 6.1.0 just released
