### ISSUE TITLE
pytest 3.3.2 breaks pytest-bdd?

### ISSUE THREAD

**Issue by alexntt** [pytest-dev/pytest-bdd#229]
Our pytest-bdd tests are failing since pytest 3.3.2 got pushed out, we get stuff like:

```
_____________________________ test_notified_backup _____________________________

request = <FixtureRequest for <Function 'test_notified_backup'>>

    @bdd.scenario('backup_execution_stored.feature', 'Notified backup')
>   def test_notified_backup():

acceptance/backups/test_backup_execution_stored.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:163: in _execute_scenario
    step_func = _find_step_function(request, step, scenario, encoding=encoding)
/usr/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:95: in _find_step_function
    name = find_argumented_step_fixture_name(name, step.type, request._fixturemanager, request)
/usr/local/lib/python2.7/site-packages/pytest_bdd/scenario.py:70: in find_argumented_step_fixture_name
    inject_fixture(request, arg, value)
/usr/local/lib/python2.7/site-packages/pytest_bdd/steps.py:307: in inject_fixture
    old_value = get_fixture_value_raw(request, arg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

request = <FixtureRequest for <Function 'test_notified_backup'>>
name = 'status'

    def get_fixture_value_raw(request, name):
        """Set the given raw fixture value from the pytest request object."""
        try:
            return request._fixture_values.get(name)
        except AttributeError:
>           return request._funcargs.get(name)
E           AttributeError: 'FixtureRequest' object has no attribute '_funcargs'

/usr/local/lib/python2.7/site-packages/pytest_bdd/utils.py:44: AttributeError
```

. although I can't see anything ringing a bell on:

https://docs.pytest.org/en/latest/changelog.html#pytest-3-3-2-2017-12-25

**Comment by The-Compiler** [comment]
I can reproduce it, bisected to https://github.com/pytest-dev/pytest/commit/c3f63ac1432044271b15c4ef7959000a7a0d9bfe

cc @nicoddemus, though it's probably not pytest core's fault, as pytest-bdd is using private APIs here...

**Comment by nicoddemus** [comment]
Yep, thanks @The-Compiler for tracking it down. The commit message says it in detail why `_fixture_values` was removed.

I see it wants to get the fixture value only if it has not been computed yet, I think this will work as a replacement (untested):

```python
def get_fixture_value_raw(request, name):
    """Set the given raw fixture value from the pytest request object."""
    fixture_def = request._fixture_defs.get(name)
    if fixture_def is not None:
    	return getattr(fixture_def, 'cached_result', None)
    return None
```

**Comment by regnarock** [comment]
@nicoddemus Thanks a lot! Could you provide the fix for the other method `set_fixture_value` as well?

**Comment by nicoddemus** [comment]
@regnarock as pytest-dev/pytest@c3f63ac shows, actually `request._fixture_values` was not being used by the core code at all, so I think `set_fixture_value` was also not having any effect (other than `get_fixture_value_raw` now returning that object of course), so I'm not sure how things are supposed to be working up until now...

**Comment by olegpidsadnyi** [comment]
@alexntt have you tried pytest-bdd 2.20.0?

**Comment by alexntt** [comment]
I hadn't, but now I have, yeah, it seems to work... for me you can close
